# Generated by Django 4.1.1 on 2022-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_brandprimecolour_brand_brandsecondarycolour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandDescription',
            field=models.TextField(max_length=500),
        ),
    ]
