# Generated by Django 4.1.1 on 2022-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_branddescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandDescription',
            field=models.TextField(max_length=800),
        ),
    ]
