# Generated by Django 4.1.1 on 2022-11-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_discount_product_mrp_product_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('productName', 'color')},
        ),
    ]
