# Generated by Django 4.1.1 on 2022-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellprice',
            field=models.IntegerField(default=0),
        ),
    ]
