# Generated by Django 4.1.1 on 2022-11-22 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shippingAddress',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
