# Generated by Django 4.1.1 on 2022-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_user_shippingaddress_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
