# Generated by Django 4.1.1 on 2022-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_userinfo_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profileImage',
            field=models.ImageField(default='', upload_to='user/'),
        ),
    ]
